# List available commands when just is called without arguments
default:
    just --list

# Build the project
build:
    cargo build --release
alias b := build

# Clean build artifacts
clean:
    cargo clean
alias c := clean

# Install the project
install:
    cargo install --path .
alias i := install

# Format code using nightly channel
format:
    rustup run nightly cargo fmt --all
alias f := format

# Run clippy lints
lint:
    cargo clippy
alias l := lint

# Build and run the project locally.
run:
    RUST_BACKTRACE=1 cargo run

# Run tests
test:
    cargo test
alias t := test

# Watch the project and run it when the code changes
watch:
    cargo watch -x 'run'
alias w := watch